name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout branch and submodules
        uses: actions/checkout@v4.1.5
        with:
          submodules: 'recursive'
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Generate AssetsTools.NET texture decoder CMake config
        run: cmake -S .\AssetsTools.NET -B .\UmaMusumeExplorer\AssetsTools.NET\build
      - name: Build AssetsTools.NET texture decoder
        run: cmake --build .\AssetsTools.NET\build
      - name: Build .NET project
        run: dotnet publish .\UmaMusumeExplorer --no-self-contained -r win-x64 -c Release -p:PublishSingleFile=true
      - name: Zip up files
        run: Compress-Archive .\UmaMusumeExplorer\bin\Release\net7.0-windows\win-x64\publish\* build-win-x64.zip
      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build-win-x64
          path: .\UmaMusumeExplorer\bin\Release\net7.0-windows\win-x64\publish\
